name: "Deploy to AWS S3"
description: "Deploy the website to an AWS S3 bucket"
inputs:
  bucket-name:
    description: "The name of the S3 bucket"
    required: true
  bucket-region:
    description: "The AWS region if set not to default"
    required: false
    default: "us-east-1"
  source-folder:
    description: "The directory to deploy"
    required: true
outputs:
  website-url:
    description: "The URL of the deployed website"
runs:
  using: "docker"
  image: "Dockerfile"
