name: "Get & Cache dependencies"
description: "Get the dependencies and cache them for future use"
inputs:
  caching:
    description: "The caching strategy to use"
    required: false
    default: "true"
    type: string
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || ${{ inputs.caching == 'false' }}
      run: npm ci
      shell: bash
