name: "Deploy to AWS S3"
description: "Deploy the website to an AWS S3 bucket"
inputs:
  bucket-name:
    description: "The name of the S3 bucket"
    required: true
  buket-region:
    description: "The AWS region"
    required: false
    default: "us-east-1"
   source-folder:
    description: "The directory to deploy"
    required: true
runs:
  using: "node20"
  main: "main.js"
